"""
Django settings for homework1 project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!+&$l&yrg)aeki!5k!yms9zbvd!7$6&o!st-fzonl7!z2u*l^%'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'sslserver',
]


LOGIN_REDIRECT_URL = '/user/'       # 使用者登入成功後導向會員中心
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/userlogin/'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'CampingData.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapp.context_processors.cart_item_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'CampingData.wsgi.application'

#發送email的設定
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # 或 465 (如果使用 SSL)
EMAIL_USE_TLS = True # 或 EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'campingdata.2025@gmail.com'
EMAIL_HOST_PASSWORD = 'dutp sswe kyhm ucoe'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
AUTH_USER_MODEL = 'myapp.User'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
     'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
        'ENGINE': 'django.db.backends.mysql', 
        'NAME': 'CampingData', 
        'USER': 'root', 
        'PASSWORD': '1234',
        'HOST': 'localhost', 
        'PORT': '8888', 
        'OPTIONS':{ 
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'", 
            'charset': 'utf8mb4',}
            }}

DATABASES["default"]=dj_database_url.parse("postgresql://campingdata_render_user:nA1kyLdHmR9REQmQNa4n6uItBTWc3YBP@dpg-d1oj06idbo4c73b4l8u0-a.oregon-postgres.render.com/campingdata_render") 

#---------產品圖片指定路徑---------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
#---------產品圖片指定路徑---------


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-Hant'

TIME_ZONE = 'Asia/Taipei'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#測試用參數(金流)
ECPAY_MERCHANT_ID = '2000132'  # 測試商店代號
ECPAY_HASH_KEY = '5294y06JbISpM5x9'
ECPAY_HASH_IV = 'v77hoKGq4kWxNNIS'
ECPAY_RETURN_URL = 'https://robot-wow-matter-cafe.trycloudflare.com/ecpay/return/'
SITE_URL = 'http://127.0.0.1:8000/'
