# Generated by Django 5.2 on 2025-07-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_trade_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
