# Generated by Django 5.2 on 2025-07-11 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_merchant_trade_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='merchant_trade_no',
        ),
    ]
